language: go
go:
  - 1.11.x
os:
  - linux
  - osx
env:
  - GO111MODULE=on
script:
   - go build ./...
#  - go test ./... # will be restored after merge of https://github.com/project-flogo/cli/pull/49
   - go version

deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
